### ISSUE TITLE
Current app problems

### ISSUE THREAD

**Issue by BunnyFiscuit** [craxido/OOPP-TDA367-DIT212#111]
+ Appen crashar ganska ofta. Är det pga minnesproblem tror ni? 
+ Monster bild laddas inte korrekt. måste byta aktivity och sen komma tillbaka till main för att den ska byta.

**Comment by Lebal** [comment]
Jag fixat en del minnesproblem.
Det används bara en bild just nu, kolla i monsterFactory, tar bara index 0

**Comment by BunnyFiscuit** [comment]
+ Nu crashar den inte som förut
+ Crashar på min mobil på andra bossen när man dödat den
  + Samsung Galaxy S6 Edge
  + Android version: 5.1.1
