### ISSUE TITLE
Namn på appen

### ISSUE THREAD

**Issue by erikdsjostrom** [craxido/OOPP-TDA367-DIT212#2]
Vi kom fram till två olika namnförslag på mötet:

- Sons of Sauron
Ett LOTR-baserat click spel

- Geometry clicker
Vi är alla överrens om att våra designkunskaper inte är något att hurra för, så varför inte hylla denna kvalité och göra att klickspel där man slåss mot olika polygoner.

Vad ska vi välja? Eller har ni någon annan idé? Låt krativiteten flöda!

**Comment by erikdsjostrom** [comment]
En annan vore att döpa den till typ "Mine click" eller "Click miner", och byta ut monstren mot stenar av varierande kvalitet. Boss-monstret kan vara typ enorma gruvråttor!

**Comment by BunnyFiscuit** [comment]
Det är i typ liknande stil av Geometry clicker bara att personen kanske tycker att en diamant är "svårare" än kanske en hexagon. pga dens värde

**Comment by erikdsjostrom** [comment]
Precis. Nackdelen som jag ser med geometry clicker är att det kan bli svårt att göra looten meningsfull, jag vet inte riktigt vad en polygon kan droppa för nått.

**Comment by BunnyFiscuit** [comment]
Man skulle kunna göra att valutan i spelet är linjer. en hexagon skulle då droppa 6 linjer, och med de linjerna skulle man kunna köpa sin egen polygon. de ba ett exempel, man kan ju förbättra idén. 

men skulle man ha stenar av olika kvalité kan man ha kvar guld som valuta samtidigt att man har kvar djur osv för hemmet

**Comment by craxido** [comment]
sorry för segt svar! tycker ädelstenar låter fett, finns ju sjukt många av dem också. 
Gem clicker? Mine clicker eller click miner lät också intressant!

**Comment by BunnyFiscuit** [comment]
click miner låter ju ba konstigt. som att man minar clicks xD

**Comment by erikdsjostrom** [comment]
Mine click, låter ganska lite Minecraft, vilken kanske är en bra sak?

Men type Click miner är ett mer beskrivande namn av det faktiska spelet.

**Comment by erikdsjostrom** [comment]
Eller Gem Miner
