### ISSUE TITLE
Gem miner?

### ISSUE THREAD

**Issue by erikdsjostrom** [craxido/OOPP-TDA367-DIT212#26]
Vi kanske borde döpa om Monster till Rocks, eller något liknande?

**Comment by BunnyFiscuit** [comment]
RockFactory XD

**Comment by craxido** [comment]
Monster -> Gem
MonsterFactory -> GemFactory
Kanske något sådant? 
Jag vet inte :D

**Comment by BunnyFiscuit** [comment]
Låter bra !

**Comment by BunnyFiscuit** [comment]
Monster Clicker
