### ISSUE TITLE
Bottom bar activity indicator

### ISSUE THREAD

**Issue by BunnyFiscuit** [craxido/OOPP-TDA367-DIT212#40]
Change the background of the activity you are at to light blue or something different then the rest. 
The use of page titles will be redundant and give more space for objects on screen

**Comment by erikdsjostrom** [comment]
Vad menar du med "page titles"?

**Comment by BunnyFiscuit** [comment]
typ att man skriver "Shop" längst upp på skärmen

**Comment by BunnyFiscuit** [comment]
use the onCreate method to change the tint of the icons
