### ISSUE TITLE
App Icon

### ISSUE THREAD

**Issue by erikdsjostrom** [craxido/OOPP-TDA367-DIT212#47]
We need a beautiful, eye-catching icon for our app!

**Comment by BunnyFiscuit** [comment]
[Check these out!](https://github.com/craxido/OOPP-TDA367-DIT212/commit/307b37c594e96d3c5fbf1f4c48c3062ace4b52b1)

**Comment by Lebal** [comment]
Gjorde du den själv?

**Comment by BunnyFiscuit** [comment]
Fonten är 100% gratis att använda. allt annat har jag gjort själv :)
