### ISSUE TITLE
Stats: Show damage with multiplier stats

### ISSUE THREAD

**Issue by BunnyFiscuit** [craxido/OOPP-TDA367-DIT212#81]
Dvs. vi vet hur mycket skada man kan göra. 
Men hur mycket skada gör man när man tar hänsyn till multipliern?

**Comment by erikdsjostrom** [comment]
Vart ska detta visas?

**Comment by BunnyFiscuit** [comment]
Det kanske inte behöver göras. visste inte att multiplier skulle vara en form av damage per sec på monstren.
